### ISSUE TITLE
possible typo in book

### ISSUE THREAD

**Issue by runkbri** [psaris/funq#10]
First congrats on the book! Looks great, very excited to go through it. Not sure if this is the right place to report typos but on p 16, section 2.4 in it refers to "3...independent features (petal and sepal measurements..." and "4...dependent feature (species label)" and then at the bottom of the page it says "we have access to the independent (species labels) and dependent (sepal and petal measurements)"  The independent/dependent labels are reversed. I believe the first labels are correct but figured i'd let you know.

**Comment by psaris** [comment]
thank you @runkbri! the correction has been recorded in 9ce8850 and will be included the next time i submit a new master copy to amazon.
