### ISSUE TITLE
How to compile the code?

### ISSUE THREAD

**Issue by yunfzhai** [psaris/funq#11]
I work under win10, win32-bit q . Useing MSYS2 to Compile., which is armed by the following packages:

- tar
- make
- patch
- mingw-w64-i686-gcc-fortran

under the target folder, type make much errors appear, as the attach file. NEED HELP!
[error.txt](https://github.com/psaris/funq/files/6866296/error.txt)

**Comment by psaris** [comment]
your setup is new to me, so not sure i can help much.  but based on the errors you provided, it seems that the compiler can not find the c functions defined in k.h.  k.h should have been downloaded to the local directory as part of the build process based on this GNUmakefile target:
```
k.h:
	wget https://raw.githubusercontent.com/KxSystems/kdb/master/c/c/k.h
```
do you see the file in your directory?

are you able to confirm that the file was downloaded correctly? if not, delete the file, run make again and check for errors in the wget command
```
$ head k.h
#ifndef KX
#define KX
typedef char*S,C;typedef unsigned char G;typedef short H;typedef int I;typedef long long J;typedef float E;typedef double F;typedef void V;
#ifdef __cplusplus
extern"C"{
#endif
#if !defined(KXVER)
#error "Set KXVER=3 for kdb+3.0 or standalone c-api after 2011-04-20. Otherwise set KXVER=2. e.g. #define KXVER 3 or gcc -DKXVER=3"
#endif
#if KXVER>=3
```

**Comment by psaris** [comment]
hello @yunfzhai. did everything work out for you?

**Comment by psaris** [comment]
closing due to lack of response
